### ISSUE TITLE
This package is not (yet) a full replacement for idiap/bob

### ISSUE THREAD

**Issue by anjos** [bioidiap/bob.nightlies#1]
We're missing a few things. As you can observe on any of the builds we have:

https://www.idiap.ch/software/bob/buildbot/builders/idiap%2Bpy3-debian-8.0-x86_64-release

We first do the buildout and then we may put the build result (using virtualenv/pip) on a directory under `/idiap/group/torch5spro/nightlies` (depends on the build). For that, we need to have a couple of tools and files to execute the task, ignore known warnings, etc.

In order to have a full valid package, we must (shallow) copy what we currently have at idiap/bob.

@tiagofrepereira2012: could you please do it?

**Comment by tiagofrepereira2012** [comment]
Done.

I basically pushed the content of the idiap/bob to this repo.
